### ISSUE TITLE
Add master playlist support

### ISSUE THREAD

**Issue by bruunand** [sea-shanty-2/HLSInterleaver#2]

**Comment by bruunand** [comment]
- [x] Add support for sub-playlists in controller
- [x] Add some mapping from sub-playlist identifiers to the actual playlist
- [x] Add proxy stream synthesizer

**Comment by anderslangballe** [comment]
Resolved in #af9db754d9278a8fcc5aec92105e0a1fd8e0bf04

**Comment by anderslangballe** [comment]
Resolved in #af9db75
